import { createContext, useContext, useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';

interface LanguageContextType {
  language: string;
  t: (key: string) => string;
  setLanguage: (language: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation mappings
const translations = {
  en: {
    'settings.title': 'Settings & Preferences',
    'settings.description': 'Customize your spiritual journey experience',
    'language.title': 'Language & Region',
    'language.description': 'Select your preferred language and regional settings',
    'language.label': 'Language',
    'general.title': 'General Preferences',
    'general.description': 'Customize your reading experience and interface preferences',
    'theme.label': 'Theme',
    'fontSize.label': 'Font Size',
    'readingSpeed.label': 'Reading Speed',
    'audioSpeed.label': 'Audio Speed',
    'timezone.label': 'Timezone',
    'familyMode.label': 'Family Mode',
    'familyMode.description': 'Enable child-safe content filtering and simplified interface',
    'notifications.title': 'Notifications',
    'notifications.description': 'Configure when and how you receive spiritual reminders',
    'prayerTimes.label': 'Prayer Times',
    'prayerTimes.description': 'Set your preferred times for prayer reminders',
    'quietHours.label': 'Quiet Hours',
    'quietHours.description': 'No notifications during these hours',
    'offline.title': 'Offline Content',
    'sync.title': 'Cross-Platform Sync',
    'ai.title': 'AI Personalization',
    'multilingual.title': 'Multilingual Content',
    'multilingual.description': 'Content is automatically translated to your preferred language while maintaining theological accuracy and cultural sensitivity.',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    'fontSize.small': 'Small',
    'fontSize.medium': 'Medium',
    'fontSize.large': 'Large',
    'readingSpeed.slow': 'Slow',
    'readingSpeed.medium': 'Medium',
    'readingSpeed.fast': 'Fast',
    'general': 'General',
    'notifications': 'Notifications',
    'offline': 'Offline',
    'sync': 'Sync',
    'ai': 'AI',
    'language': 'Language',
    'nav.home': 'Home',
    'nav.messages': 'Messages',
    'nav.contacts': 'Contacts',
    'nav.churches': 'Churches',
    'nav.events': 'Events',
    'nav.discussions': 'Discussions',
    'nav.donation': 'Donation',
    'nav.todaysReading': "Today's Reading",
    'nav.prayerWall': 'Prayer Wall',
    'nav.soapJournal': 'S.O.A.P. Journal',
    'nav.audioBible': 'Audio Bible',
    'nav.audioRoutines': 'Audio Routines',
    'nav.videoLibrary': 'Video Library',
    'nav.imageGallery': 'Image Gallery',
    'nav.memberDirectory': 'Member Directory',
    'nav.donationAnalytics': 'Donation Analytics',
    'nav.communicationHub': 'Communication Hub',
    'nav.sermonStudio': 'Sermon Studio',
    'nav.engagementAnalytics': 'Engagement Analytics',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'sections.community': 'COMMUNITY',
    'sections.spiritualTools': 'SPIRITUAL TOOLS',
    'sections.mediaContents': 'MEDIA CONTENTS',
    'sections.adminPortal': 'ADMIN PORTAL',
    'sections.account': 'ACCOUNT',
    'nav.engagementBoard': 'Engagement Board',
    'posts.recentCheckIns': 'Recent Check-Ins',
    'posts.latestPosts': 'Latest Posts',
    'posts.showMorePosts': 'Show More Posts',
    'posts.pleaseShareThoughts': 'Please share your thoughts...',
    'posts.testPost': 'Test post',
    'posts.unableToLoadPosts': 'Unable to load posts',
    'posts.loading': 'Loading...',
    'posts.noPostsYet': 'No posts yet',
    'posts.beFirstToShare': 'Be the first to share something',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'buttons.post': 'Post',
    'buttons.like': 'Like',
    'buttons.comment': 'Comment',
    'buttons.share': 'Share',
    'posts.howAreYouFeeling': 'How are you feeling?',
    'posts.postShared': 'Post shared!',
    'posts.sharedWithCommunity': 'Your post has been shared with your community.'
  },
  es: {
    'settings.title': 'Configuración y Preferencias',
    'settings.description': 'Personaliza tu experiencia de viaje espiritual',
    'language.title': 'Idioma y Región',
    'language.description': 'Selecciona tu idioma preferido y configuración regional',
    'language.label': 'Idioma',
    'general.title': 'Preferencias Generales',
    'general.description': 'Personaliza tu experiencia de lectura y preferencias de interfaz',
    'theme.label': 'Tema',
    'fontSize.label': 'Tamaño de Fuente',
    'readingSpeed.label': 'Velocidad de Lectura',
    'audioSpeed.label': 'Velocidad de Audio',
    'timezone.label': 'Zona Horaria',
    'familyMode.label': 'Modo Familiar',
    'familyMode.description': 'Habilitar filtrado de contenido seguro para niños e interfaz simplificada',
    'notifications.title': 'Notificaciones',
    'notifications.description': 'Configura cuándo y cómo recibir recordatorios espirituales',
    'prayerTimes.label': 'Horarios de Oración',
    'prayerTimes.description': 'Establece tus horarios preferidos para recordatorios de oración',
    'quietHours.label': 'Horas de Silencio',
    'quietHours.description': 'Sin notificaciones durante estas horas',
    'offline.title': 'Contenido Sin Conexión',
    'sync.title': 'Sincronización Multiplataforma',
    'ai.title': 'Personalización IA',
    'multilingual.title': 'Contenido Multilingüe',
    'multilingual.description': 'El contenido se traduce automáticamente a tu idioma preferido manteniendo la precisión teológica y sensibilidad cultural.',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.auto': 'Automático',
    'fontSize.small': 'Pequeño',
    'fontSize.medium': 'Mediano',
    'fontSize.large': 'Grande',
    'readingSpeed.slow': 'Lento',
    'readingSpeed.medium': 'Medio',
    'readingSpeed.fast': 'Rápido',
    'general': 'General',
    'notifications': 'Notific.',
    'offline': 'Sin Red',
    'sync': 'Sinc.',
    'ai': 'IA',
    'language': 'Idioma',
    'nav.home': 'Inicio',
    'nav.messages': 'Mensajes',
    'nav.contacts': 'Contactos',
    'nav.churches': 'Iglesias',
    'nav.events': 'Eventos',
    'nav.discussions': 'Discusiones',
    'nav.donation': 'Donación',
    'nav.todaysReading': 'Lectura de Hoy',
    'nav.prayerWall': 'Muro de Oración',
    'nav.soapJournal': 'Diario S.O.A.P.',
    'nav.audioBible': 'Biblia Audio',
    'nav.audioRoutines': 'Rutinas Audio',
    'nav.videoLibrary': 'Biblioteca Video',
    'nav.imageGallery': 'Galería Imágenes',
    'nav.memberDirectory': 'Directorio Miembros',
    'nav.donationAnalytics': 'Análisis Donaciones',
    'nav.communicationHub': 'Centro Comunicación',
    'nav.sermonStudio': 'Estudio Sermón',
    'nav.engagementAnalytics': 'Análisis Participación',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'sections.community': 'COMUNIDAD',
    'sections.spiritualTools': 'HERRAMIENTAS ESPIRITUALES',
    'sections.mediaContents': 'CONTENIDO MULTIMEDIA',
    'sections.adminPortal': 'PORTAL ADMIN',
    'sections.account': 'CUENTA',
    'nav.engagementBoard': 'Tablero de Participación',
    'posts.recentCheckIns': 'Registros Recientes',
    'posts.latestPosts': 'Últimas Publicaciones',
    'posts.showMorePosts': 'Mostrar Más Publicaciones',
    'posts.pleaseShareThoughts': 'Por favor comparte tus pensamientos...',
    'posts.testPost': 'Publicación de prueba',
    'posts.unableToLoadPosts': 'No se pueden cargar las publicaciones',
    'posts.loading': 'Cargando...',
    'posts.noPostsYet': 'Aún no hay publicaciones',
    'posts.beFirstToShare': 'Sé el primero en compartir algo',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.submit': 'Enviar',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'buttons.post': 'Publicar',
    'buttons.like': 'Me gusta',
    'buttons.comment': 'Comentar',
    'buttons.share': 'Compartir',
    'posts.howAreYouFeeling': '¿Cómo te sientes?',
    'posts.postShared': '¡Publicación compartida!',
    'posts.sharedWithCommunity': 'Tu publicación ha sido compartida con tu comunidad.'
  },
  fr: {
    'settings.title': 'Paramètres et Préférences',
    'settings.description': 'Personnalisez votre expérience de voyage spirituel',
    'language.title': 'Langue et Région',
    'language.description': 'Sélectionnez votre langue préférée et paramètres régionaux',
    'language.label': 'Langue',
    'general.title': 'Préférences Générales',
    'general.description': 'Personnalisez votre expérience de lecture et préférences d\'interface',
    'theme.label': 'Thème',
    'fontSize.label': 'Taille de Police',
    'readingSpeed.label': 'Vitesse de Lecture',
    'audioSpeed.label': 'Vitesse Audio',
    'timezone.label': 'Fuseau Horaire',
    'familyMode.label': 'Mode Famille',
    'familyMode.description': 'Activer le filtrage de contenu sûr pour enfants et interface simplifiée',
    'notifications.title': 'Notifications',
    'notifications.description': 'Configurez quand et comment recevoir des rappels spirituels',
    'prayerTimes.label': 'Heures de Prière',
    'prayerTimes.description': 'Définissez vos heures préférées pour les rappels de prière',
    'quietHours.label': 'Heures Silencieuses',
    'quietHours.description': 'Aucune notification pendant ces heures',
    'offline.title': 'Contenu Hors Ligne',
    'sync.title': 'Synchronisation Multi-plateforme',
    'ai.title': 'Personnalisation IA',
    'multilingual.title': 'Contenu Multilingue',
    'multilingual.description': 'Le contenu est automatiquement traduit dans votre langue préférée tout en maintenant la précision théologique et la sensibilité culturelle.',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.auto': 'Auto',
    'fontSize.small': 'Petit',
    'fontSize.medium': 'Moyen',
    'fontSize.large': 'Grand',
    'readingSpeed.slow': 'Lent',
    'readingSpeed.medium': 'Moyen',
    'readingSpeed.fast': 'Rapide',
    'general': 'Général',
    'notifications': 'Notif.',
    'offline': 'Hors ligne',
    'sync': 'Sync',
    'ai': 'IA',
    'language': 'Langue',
    'nav.home': 'Accueil',
    'nav.messages': 'Messages',
    'nav.contacts': 'Contacts',
    'nav.churches': 'Églises',
    'nav.events': 'Événements',
    'nav.discussions': 'Discussions',
    'nav.donation': 'Don',
    'nav.todaysReading': "Lecture d'Aujourd'hui",
    'nav.prayerWall': 'Mur de Prière',
    'nav.soapJournal': 'Journal S.O.A.P.',
    'nav.audioBible': 'Bible Audio',
    'nav.audioRoutines': 'Routines Audio',
    'nav.videoLibrary': 'Bibliothèque Vidéo',
    'nav.imageGallery': "Galerie d'Images",
    'nav.memberDirectory': 'Répertoire Membres',
    'nav.donationAnalytics': 'Analyses Dons',
    'nav.communicationHub': 'Centre Communication',
    'nav.sermonStudio': 'Studio Sermon',
    'nav.engagementAnalytics': 'Analyses Engagement',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'sections.community': 'COMMUNAUTÉ',
    'sections.spiritualTools': 'OUTILS SPIRITUELS',
    'sections.mediaContents': 'CONTENU MÉDIA',
    'sections.adminPortal': 'PORTAIL ADMIN',
    'sections.account': 'COMPTE',
    'nav.engagementBoard': 'Tableau dEngagement',
    'posts.recentCheckIns': 'Enregistrements Récents',
    'posts.latestPosts': 'Dernières Publications',
    'posts.showMorePosts': 'Afficher Plus de Publications',
    'posts.pleaseShareThoughts': 'Veuillez partager vos pensées...',
    'posts.testPost': 'Publication de test',
    'posts.unableToLoadPosts': 'Impossible de charger les publications',
    'posts.loading': 'Chargement...',
    'posts.noPostsYet': 'Aucune publication pour le moment',
    'posts.beFirstToShare': 'Soyez le premier à partager quelque chose',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.submit': 'Soumettre',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'buttons.post': 'Publier',
    'buttons.like': 'Aimer',
    'buttons.comment': 'Commenter',
    'buttons.share': 'Partager',
    'posts.howAreYouFeeling': 'Comment vous sentez-vous?',
    'posts.postShared': 'Publication partagée!',
    'posts.sharedWithCommunity': 'Votre publication a été partagée avec votre communauté.'
  },
  hi: {
    'settings.title': 'सेटिंग्स और प्राथमिकताएं',
    'settings.description': 'अपनी आध्यात्मिक यात्रा के अनुभव को कस्टमाइज़ करें',
    'language.title': 'भाषा और क्षेत्र',
    'language.description': 'अपनी पसंदीदा भाषा और क्षेत्रीय सेटिंग्स चुनें',
    'language.label': 'भाषा',
    'general.title': 'सामान्य प्राथमिकताएं',
    'general.description': 'अपने पढ़ने के अनुभव और इंटरफ़ेस प्राथमिकताओं को कस्टमाइज़ करें',
    'theme.label': 'थीम',
    'fontSize.label': 'फ़ॉन्ट साइज़',
    'readingSpeed.label': 'पढ़ने की गति',
    'audioSpeed.label': 'ऑडियो गति',
    'timezone.label': 'समय क्षेत्र',
    'familyMode.label': 'पारिवारिक मोड',
    'familyMode.description': 'बच्चों के लिए सुरक्षित सामग्री फ़िल्टरिंग और सरल इंटरफ़ेस सक्षम करें',
    'notifications.title': 'सूचनाएं',
    'notifications.description': 'कॉन्फ़िगर करें कि आप कब और कैसे आध्यात्मिक अनुस्मारक प्राप्त करते हैं',
    'prayerTimes.label': 'प्रार्थना समय',
    'prayerTimes.description': 'प्रार्थना अनुस्मारक के लिए अपना पसंदीदा समय सेट करें',
    'quietHours.label': 'शांत घंटे',
    'quietHours.description': 'इन घंटों के दौरान कोई सूचना नहीं',
    'offline.title': 'ऑफ़लाइन सामग्री',
    'sync.title': 'क्रॉस-प्लेटफ़ॉर्म सिंक',
    'ai.title': 'AI व्यक्तिगतकरण',
    'multilingual.title': 'बहुभाषी सामग्री',
    'multilingual.description': 'सामग्री स्वचालित रूप से आपकी पसंदीदा भाषा में अनुवादित होती है जबकि धर्मशास्त्रीय सटीकता और सांस्कृतिक संवेदनशीलता बनाए रखती है।',
    'theme.light': 'हल्का',
    'theme.dark': 'गहरा',
    'theme.auto': 'स्वचालित',
    'fontSize.small': 'छोटा',
    'fontSize.medium': 'मध्यम',
    'fontSize.large': 'बड़ा',
    'readingSpeed.slow': 'धीमा',
    'readingSpeed.medium': 'मध्यम',
    'readingSpeed.fast': 'तेज़',
    'general': 'सामान्य',
    'notifications': 'सूचनाएं',
    'offline': 'ऑफ़लाइन',
    'sync': 'सिंक',
    'ai': 'AI',
    'language': 'भाषा',
    'nav.home': 'होम',
    'nav.messages': 'संदेश',
    'nav.contacts': 'संपर्क',
    'nav.churches': 'चर्च',
    'nav.events': 'कार्यक्रम',
    'nav.discussions': 'चर्चा',
    'nav.donation': 'दान',
    'nav.todaysReading': 'आज का पठन',
    'nav.prayerWall': 'प्रार्थना दीवार',
    'nav.soapJournal': 'S.O.A.P. जर्नल',
    'nav.audioBible': 'ऑडियो बाइबल',
    'nav.audioRoutines': 'ऑडियो रूटीन',
    'nav.videoLibrary': 'वीडियो लाइब्रेरी',
    'nav.imageGallery': 'इमेज गैलरी',
    'nav.memberDirectory': 'सदस्य निर्देशिका',
    'nav.donationAnalytics': 'दान एनालिटिक्स',
    'nav.communicationHub': 'संचार केंद्र',
    'nav.sermonStudio': 'उपदेश स्टूडियो',
    'nav.engagementAnalytics': 'सहभागिता एनालिटिक्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'sections.community': 'समुदाय',
    'sections.spiritualTools': 'आध्यात्मिक उपकरण',
    'sections.mediaContents': 'मीडिया सामग्री',
    'sections.adminPortal': 'एडमिन पोर्टल',
    'sections.account': 'खाता',
    'nav.engagementBoard': 'सहभागिता बोर्ड',
    'posts.recentCheckIns': 'हाल की चेक-इन्स',
    'posts.latestPosts': 'नवीनतम पोस्ट',
    'posts.showMorePosts': 'और पोस्ट दिखाएं',
    'posts.pleaseShareThoughts': 'कृपया अपने विचार साझा करें...',
    'posts.testPost': 'परीक्षण पोस्ट',
    'posts.unableToLoadPosts': 'पोस्ट लोड नहीं कर सकते',
    'posts.loading': 'लोड हो रहा है...',
    'posts.noPostsYet': 'अभी तक कोई पोस्ट नहीं',
    'posts.beFirstToShare': 'कुछ साझा करने वाले पहले व्यक्ति बनें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.submit': 'सबमिट करें',
    'common.close': 'बंद करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'buttons.post': 'पोस्ट करें',
    'buttons.like': 'पसंद',
    'buttons.comment': 'टिप्पणी',
    'buttons.share': 'साझा करें',
    'posts.howAreYouFeeling': 'आप कैसा महसूस कर रहे हैं?',
    'posts.postShared': 'पोस्ट साझा किया गया!',
    'posts.sharedWithCommunity': 'आपका पोस्ट आपके समुदाय के साथ साझा किया गया है।'
  },
  ar: {
    'settings.title': 'الإعدادات والتفضيلات',
    'settings.description': 'خصص تجربة رحلتك الروحية',
    'language.title': 'اللغة والمنطقة',
    'language.description': 'اختر لغتك المفضلة والإعدادات الإقليمية',
    'language.label': 'اللغة',
    'general.title': 'التفضيلات العامة',
    'general.description': 'خصص تجربة القراءة وتفضيلات الواجهة',
    'theme.label': 'المظهر',
    'fontSize.label': 'حجم الخط',
    'readingSpeed.label': 'سرعة القراءة',
    'audioSpeed.label': 'سرعة الصوت',
    'timezone.label': 'المنطقة الزمنية',
    'familyMode.label': 'وضع العائلة',
    'familyMode.description': 'تمكين تصفية المحتوى الآمن للأطفال والواجهة المبسطة',
    'notifications.title': 'الإشعارات',
    'notifications.description': 'تكوين متى وكيف تتلقى التذكيرات الروحية',
    'prayerTimes.label': 'أوقات الصلاة',
    'prayerTimes.description': 'حدد أوقاتك المفضلة لتذكيرات الصلاة',
    'quietHours.label': 'ساعات الهدوء',
    'quietHours.description': 'لا إشعارات خلال هذه الساعات',
    'offline.title': 'المحتوى غير المتصل',
    'sync.title': 'المزامنة عبر المنصات',
    'ai.title': 'التخصيص بالذكاء الاصطناعي',
    'multilingual.title': 'المحتوى متعدد اللغات',
    'multilingual.description': 'يتم ترجمة المحتوى تلقائياً إلى لغتك المفضلة مع الحفاظ على الدقة اللاهوتية والحساسية الثقافية.',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.auto': 'تلقائي',
    'fontSize.small': 'صغير',
    'fontSize.medium': 'متوسط',
    'fontSize.large': 'كبير',
    'readingSpeed.slow': 'بطيء',
    'readingSpeed.medium': 'متوسط',
    'readingSpeed.fast': 'سريع',
    'general': 'عام',
    'notifications': 'الإشعارات',
    'offline': 'غير متصل',
    'sync': 'مزامنة',
    'ai': 'ذكاء اصطناعي',
    'language': 'لغة',
    'nav.home': 'الرئيسية',
    'nav.messages': 'الرسائل',
    'nav.contacts': 'جهات الاتصال',
    'nav.churches': 'الكنائس',
    'nav.events': 'الأحداث',
    'nav.discussions': 'المناقشات',
    'nav.donation': 'التبرع',
    'nav.todaysReading': 'قراءة اليوم',
    'nav.prayerWall': 'جدار الصلاة',
    'nav.soapJournal': 'مجلة S.O.A.P.',
    'nav.audioBible': 'الكتاب المقدس الصوتي',
    'nav.audioRoutines': 'الروتين الصوتي',
    'nav.videoLibrary': 'مكتبة الفيديو',
    'nav.imageGallery': 'معرض الصور',
    'nav.memberDirectory': 'دليل الأعضاء',
    'nav.donationAnalytics': 'تحليلات التبرع',
    'nav.communicationHub': 'مركز التواصل',
    'nav.sermonStudio': 'استوديو الخطبة',
    'nav.engagementAnalytics': 'تحليلات المشاركة',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'sections.community': 'المجتمع',
    'sections.spiritualTools': 'الأدوات الروحية',
    'sections.mediaContents': 'محتويات الوسائط',
    'sections.adminPortal': 'بوابة الإدارة',
    'sections.account': 'الحساب',
    'nav.engagementBoard': 'لوحة المشاركة',
    'posts.recentCheckIns': 'تسجيلات الحضور الأخيرة',
    'posts.latestPosts': 'أحدث المنشورات',
    'posts.showMorePosts': 'عرض المزيد من المنشورات',
    'posts.pleaseShareThoughts': 'من فضلك شارك أفكارك...',
    'checkins.recent': 'الحضور الأخير',
    'checkins.viewAll': 'عرض الكل',
    'checkins.quickActions': 'إجراءات سريعة',
    'checkins.checkIn': 'تسجيل الحضور',
    'checkins.viewHistory': 'عرض التاريخ',
    'posts.testPost': 'منشور تجريبي',
    'posts.unableToLoadPosts': 'غير قادر على تحميل المنشورات',
    'posts.loading': 'جاري التحميل...',
    'posts.noPostsYet': 'لا توجد منشورات بعد',
    'posts.beFirstToShare': 'كن أول من يشارك شيئاً',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'buttons.post': 'نشر',
    'buttons.like': 'إعجاب',
    'buttons.comment': 'تعليق',
    'buttons.share': 'مشاركة',
    'posts.howAreYouFeeling': 'كيف تشعر؟',
    'posts.postShared': 'تم مشاركة المنشور!',
    'posts.sharedWithCommunity': 'تم مشاركة منشورك مع مجتمعك.',
    'readingSpeed.label': 'سرعة القراءة',
    'timezone.label': 'المنطقة الزمنية',
    'audioSpeed.label': 'سرعة الصوت',
    'familyMode.label': 'وضع العائلة',
    'familyMode.description': 'إظهار محتوى ورسوم توضيحية مناسبة للأطفال',
    'audioEnabled.label': 'تمكين الصوت',
    'audioEnabled.description': 'تمكين السرد الصوتي للقراءات',
    'posts.postedBy': 'نشر بواسطة',
    'posts.timeAgo.justNow': 'الآن',
    'posts.timeAgo.minutesAgo': 'منذ دقائق',
    'posts.timeAgo.hoursAgo': 'منذ ساعات',
    'posts.timeAgo.daysAgo': 'منذ أيام',
    'posts.timeAgo.weeksAgo': 'منذ أسابيع',
    'posts.expand': 'توسيع',
    'posts.collapse': 'طي',
    'posts.readMore': 'اقرأ المزيد',
    'posts.showLess': 'عرض أقل',
    'timezone.utc': 'التوقيت العالمي المنسق',
    'timezone.eastern': 'التوقيت الشرقي',
    'timezone.central': 'التوقيت المركزي',
    'timezone.mountain': 'التوقيت الجبلي',
    'timezone.pacific': 'توقيت المحيط الهادئ',
    'readingSpeed.slow': 'بطيء',
    'readingSpeed.medium': 'عادي',
    'readingSpeed.fast': 'سريع'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState('en');

  // Fetch user preferences
  const { data: preferences } = useQuery({
    queryKey: ['/api/user/preferences'],
  });

  // Update language when preferences change
  useEffect(() => {
    if (preferences?.language) {
      setLanguage(preferences.language);
    }
  }, [preferences]);

  // Translation function
  const t = (key: string): string => {
    const currentTranslations = translations[language as keyof typeof translations] || translations.en;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}