import { createContext, useContext, useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';

interface LanguageContextType {
  language: string;
  t: (key: string) => string;
  setLanguage: (language: string) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation mappings
const translations = {
  en: {
    'settings.title': 'Settings & Preferences',
    'settings.description': 'Customize your spiritual journey experience',
    'language.title': 'Language & Region',
    'language.description': 'Select your preferred language and regional settings',
    'language.label': 'Language',
    'general.title': 'General Preferences',
    'general.description': 'Customize your reading experience and interface preferences',
    'theme.label': 'Theme',
    'fontSize.label': 'Font Size',
    'readingSpeed.label': 'Reading Speed',
    'audioSpeed.label': 'Audio Speed',
    'timezone.label': 'Timezone',
    'familyMode.label': 'Family Mode',
    'familyMode.description': 'Enable child-safe content filtering and simplified interface',
    'notifications.title': 'Notifications',
    'notifications.description': 'Configure when and how you receive spiritual reminders',
    'prayerTimes.label': 'Prayer Times',
    'prayerTimes.description': 'Set your preferred times for prayer reminders',
    'quietHours.label': 'Quiet Hours',
    'quietHours.description': 'No notifications during these hours',
    'offline.title': 'Offline Content',
    'sync.title': 'Cross-Platform Sync',
    'ai.title': 'AI Personalization',
    'multilingual.title': 'Multilingual Content',
    'multilingual.description': 'Content is automatically translated to your preferred language while maintaining theological accuracy and cultural sensitivity.',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    'fontSize.small': 'Small',
    'fontSize.medium': 'Medium',
    'fontSize.large': 'Large',
    'readingSpeed.slow': 'Slow',
    'readingSpeed.medium': 'Medium',
    'readingSpeed.fast': 'Fast',
    'general': 'General',
    'notifications': 'Notifications',
    'offline': 'Offline',
    'sync': 'Sync',
    'ai': 'AI',
    'language': 'Language',
    'nav.home': 'Home',
    'nav.messages': 'Messages',
    'nav.contacts': 'Contacts',
    'nav.churches': 'Churches',
    'nav.events': 'Events',
    'nav.discussions': 'Discussions',
    'nav.donation': 'Donation',
    'nav.todaysReading': "Today's Reading",
    'nav.prayerWall': 'Prayer Wall',
    'nav.soapJournal': 'S.O.A.P. Journal',
    'nav.audioBible': 'Audio Bible',
    'nav.audioRoutines': 'Audio Routines',
    'nav.videoLibrary': 'Video Library',
    'nav.imageGallery': 'Image Gallery',
    'nav.memberDirectory': 'Member Directory',
    'nav.donationAnalytics': 'Donation Analytics',
    'nav.communicationHub': 'Communication Hub',
    'nav.sermonStudio': 'Sermon Studio',
    'nav.engagementAnalytics': 'Engagement Analytics',
    'nav.engagementBoard': 'Community Engagement Board',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'sections.community': 'COMMUNITY',
    'sections.spiritualTools': 'SPIRITUAL TOOLS',
    'sections.mediaContents': 'MEDIA CONTENTS',
    'sections.adminPortal': 'ADMIN PORTAL',
    'sections.account': 'ACCOUNT',
    'nav.engagementBoard': 'Engagement Board',
    'posts.recentCheckIns': 'Recent Check-Ins',
    'posts.latestPosts': 'Latest Posts',
    'posts.showMorePosts': 'Show More Posts',
    'posts.pleaseShareThoughts': 'Please share your thoughts...',
    'posts.testPost': 'Test post',
    'posts.unableToLoadPosts': 'Unable to load posts',
    'posts.loading': 'Loading...',
    'posts.noPostsYet': 'No posts yet',
    'posts.beFirstToShare': 'Be the first to share something',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'buttons.post': 'Post',
    'buttons.like': 'Like',
    'buttons.comment': 'Comment',
    'buttons.share': 'Share',
    'posts.howAreYouFeeling': 'How are you feeling?',
    'posts.postShared': 'Post shared!',
    'posts.sharedWithCommunity': 'Your post has been shared with your community.',
    'buttons.importContacts': 'Import Contacts',
    'buttons.inviteFriends': 'Invite Friends',
    'buttons.shareSoapBox': 'Share SoapBox',
    'buttons.myContacts': 'My Contacts',
    'buttons.pendingInvites': 'Pending Invites',
    'buttons.referralProgram': 'Referral Program',
    'buttons.sendInvitation': 'Send Invitation',
    'buttons.copyLink': 'Copy Link',
    'buttons.shareLink': 'Share Link',
    'buttons.viewDetails': 'View Details',
    'buttons.sendMessage': 'Send Message',
    'buttons.connect': 'Connect',
    'buttons.remove': 'Remove',
    'buttons.block': 'Block',
    'buttons.unblock': 'Unblock',
    'buttons.report': 'Report',
    'timezone.utc': 'UTC',
    'timezone.eastern': 'Eastern Time',
    'timezone.central': 'Central Time',
    'timezone.mountain': 'Mountain Time',
    'timezone.pacific': 'Pacific Time',
    'audioEnabled.label': 'Audio Enabled',
    'audioEnabled.description': 'Enable audio narration and sound effects',
    'buttons.newMessage': 'New Message',
    'prayerWall.title': 'Prayer Wall',
    'prayerWall.newPrayerRequest': 'New Prayer Request',
    'prayerWall.categories': 'Prayer Categories',
    'prayerWall.allPrayers': 'All Prayers',
    'prayerWall.health': 'Health',
    'prayerWall.career': 'Career',
    'prayerWall.relationships': 'Relationships',
    'prayerWall.spiritualGrowth': 'Spiritual Growth',
    'prayerWall.family': 'Family',
    'prayerWall.urgent': 'Urgent',
    'prayerWall.general': 'General',
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.statistics': 'Statistics',
    'profile.achievements': 'Achievements',
    'profile.contactInformation': 'Contact Information',
    'profile.memberSince': 'Member since'
  },
  es: {
    'settings.title': 'Configuración y Preferencias',
    'settings.description': 'Personaliza tu experiencia de viaje espiritual',
    'language.title': 'Idioma y Región',
    'language.description': 'Selecciona tu idioma preferido y configuración regional',
    'language.label': 'Idioma',
    'general.title': 'Preferencias Generales',
    'general.description': 'Personaliza tu experiencia de lectura y preferencias de interfaz',
    'theme.label': 'Tema',
    'fontSize.label': 'Tamaño de Fuente',
    'readingSpeed.label': 'Velocidad de Lectura',
    'audioSpeed.label': 'Velocidad de Audio',
    'timezone.label': 'Zona Horaria',
    'familyMode.label': 'Modo Familiar',
    'familyMode.description': 'Habilitar filtrado de contenido seguro para niños e interfaz simplificada',
    'notifications.title': 'Notificaciones',
    'notifications.description': 'Configura cuándo y cómo recibir recordatorios espirituales',
    'prayerTimes.label': 'Horarios de Oración',
    'prayerTimes.description': 'Establece tus horarios preferidos para recordatorios de oración',
    'quietHours.label': 'Horas de Silencio',
    'quietHours.description': 'Sin notificaciones durante estas horas',
    'offline.title': 'Contenido Sin Conexión',
    'sync.title': 'Sincronización Multiplataforma',
    'ai.title': 'Personalización IA',
    'multilingual.title': 'Contenido Multilingüe',
    'multilingual.description': 'El contenido se traduce automáticamente a tu idioma preferido manteniendo la precisión teológica y sensibilidad cultural.',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.auto': 'Automático',
    'fontSize.small': 'Pequeño',
    'fontSize.medium': 'Mediano',
    'fontSize.large': 'Grande',
    'readingSpeed.slow': 'Lento',
    'readingSpeed.medium': 'Medio',
    'readingSpeed.fast': 'Rápido',
    'general': 'General',
    'notifications': 'Notific.',
    'offline': 'Sin Red',
    'sync': 'Sinc.',
    'ai': 'IA',
    'language': 'Idioma',
    'nav.home': 'Inicio',
    'nav.messages': 'Mensajes',
    'nav.contacts': 'Contactos',
    'nav.churches': 'Iglesias',
    'nav.events': 'Eventos',
    'nav.discussions': 'Discusiones',
    'nav.donation': 'Donación',
    'nav.todaysReading': 'Lectura de Hoy',
    'nav.prayerWall': 'Muro de Oración',
    'nav.soapJournal': 'Diario S.O.A.P.',
    'nav.audioBible': 'Biblia Audio',
    'nav.audioRoutines': 'Rutinas Audio',
    'nav.videoLibrary': 'Biblioteca Video',
    'nav.imageGallery': 'Galería Imágenes',
    'nav.memberDirectory': 'Directorio Miembros',
    'nav.donationAnalytics': 'Análisis Donaciones',
    'nav.communicationHub': 'Centro Comunicación',
    'nav.sermonStudio': 'Estudio Sermón',
    'nav.engagementAnalytics': 'Análisis Participación',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'sections.community': 'COMUNIDAD',
    'sections.spiritualTools': 'HERRAMIENTAS ESPIRITUALES',
    'sections.mediaContents': 'CONTENIDO MULTIMEDIA',
    'sections.adminPortal': 'PORTAL ADMIN',
    'sections.account': 'CUENTA',
    'nav.engagementBoard': 'Tablero de Participación',
    'posts.recentCheckIns': 'Registros Recientes',
    'posts.latestPosts': 'Últimas Publicaciones',
    'posts.showMorePosts': 'Mostrar Más Publicaciones',
    'posts.pleaseShareThoughts': 'Por favor comparte tus pensamientos...',
    'posts.testPost': 'Publicación de prueba',
    'posts.unableToLoadPosts': 'No se pueden cargar las publicaciones',
    'posts.loading': 'Cargando...',
    'posts.noPostsYet': 'Aún no hay publicaciones',
    'posts.beFirstToShare': 'Sé el primero en compartir algo',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.submit': 'Enviar',
    'common.close': 'Cerrar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'buttons.post': 'Publicar',
    'buttons.like': 'Me gusta',
    'buttons.comment': 'Comentar',
    'buttons.share': 'Compartir',
    'posts.howAreYouFeeling': '¿Cómo te sientes?',
    'posts.postShared': '¡Publicación compartida!',
    'posts.sharedWithCommunity': 'Tu publicación ha sido compartida con tu comunidad.',
    'pages.messages': 'Mensajes',
    'pages.conversations': 'Conversaciones',
    'pages.communityConnections': 'Conexiones Comunitarias',
    'pages.myChurches': 'Mis Iglesias',
    'pages.discoverMoreChurches': 'Descubrir Más Iglesias',
    'pages.communityEvents': 'Eventos Comunitarios',
    'pages.upcomingEvents': 'Próximos Eventos',
    'pages.discussions': 'Discusiones',
    'pages.todaysReading': 'Lectura de Hoy',
    'pages.dailyVerse': 'Versículo Diario',
    'pages.prayerWall': 'Muro de Oración',
    'pages.prayerRequests': 'Peticiones de Oración',
    'pages.prayerCircles': 'Círculos de Oración',
    'pages.analyticsAndBadges': 'Análisis y Insignias',
    'pages.soapJournal': 'Diario S.O.A.P',
    'pages.audioBibleExperience': 'Experiencia Biblia Audio',
    'pages.audioRoutines': 'Rutinas de Audio',
    'pages.communityEngagementBoard': 'Tablero de Participación Comunitaria',
    'pages.churches': 'Iglesias',
    'pages.events': 'Eventos',
    'pages.videoLibrary': 'Biblioteca de Videos',
    'pages.imageGallery': 'Galería de Imágenes',
    'pages.memberDirectory': 'Directorio de Miembros',
    'pages.donationAnalytics': 'Análisis de Donaciones',
    'pages.communicationHub': 'Centro de Comunicación',
    'pages.sermonStudio': 'Estudio de Sermones',
    'pages.engagementAnalytics': 'Análisis de Participación',
    'pages.churchManagement': 'Gestión de Iglesia',
    'pages.profile': 'Perfil',
    'pages.settings': 'Configuración',
    'common.groups': 'Grupos',
    'common.create': 'Crear',
    'common.new': 'Nuevo',
    'common.search': 'Buscar',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.confirm': 'Confirmar',
    'buttons.importContacts': 'Importar Contactos',
    'buttons.inviteFriends': 'Invitar Amigos',
    'buttons.shareSoapBox': 'Compartir SoapBox',
    'buttons.myContacts': 'Mis Contactos',
    'buttons.pendingInvites': 'Invitaciones Pendientes',
    'buttons.referralProgram': 'Programa de Referidos',
    'buttons.sendInvitation': 'Enviar Invitación',
    'buttons.copyLink': 'Copiar Enlace',
    'buttons.shareLink': 'Compartir Enlace',
    'buttons.viewDetails': 'Ver Detalles',
    'buttons.sendMessage': 'Enviar Mensaje',
    'buttons.connect': 'Conectar',
    'buttons.remove': 'Eliminar',
    'buttons.block': 'Bloquear',
    'buttons.unblock': 'Desbloquear',
    'buttons.report': 'Reportar',
    'timezone.utc': 'UTC',
    'timezone.eastern': 'Hora del Este',
    'timezone.central': 'Hora Central',
    'timezone.mountain': 'Hora de Montaña',
    'timezone.pacific': 'Hora del Pacífico',
    'audioEnabled.label': 'Audio Habilitado',
    'audioEnabled.description': 'Habilitar narración de audio y efectos de sonido',
    'buttons.newMessage': 'Nuevo Mensaje',
    'prayerWall.title': 'Muro de Oración',
    'prayerWall.newPrayerRequest': 'Nueva Petición de Oración',
    'prayerWall.categories': 'Categorías de Oración',
    'prayerWall.allPrayers': 'Todas las Oraciones',
    'prayerWall.health': 'Salud',
    'prayerWall.career': 'Carrera',
    'prayerWall.relationships': 'Relaciones',
    'prayerWall.spiritualGrowth': 'Crecimiento Espiritual',
    'prayerWall.family': 'Familia',
    'prayerWall.urgent': 'Urgente',
    'prayerWall.general': 'General',
    'profile.title': 'Perfil',
    'profile.editProfile': 'Editar Perfil',
    'profile.statistics': 'Estadísticas',
    'profile.achievements': 'Logros',
    'profile.contactInformation': 'Información de Contacto',
    'profile.memberSince': 'Miembro desde'
  },
  fr: {
    'settings.title': 'Paramètres et Préférences',
    'settings.description': 'Personnalisez votre expérience de voyage spirituel',
    'language.title': 'Langue et Région',
    'language.description': 'Sélectionnez votre langue préférée et paramètres régionaux',
    'language.label': 'Langue',
    'general.title': 'Préférences Générales',
    'general.description': 'Personnalisez votre expérience de lecture et préférences d\'interface',
    'theme.label': 'Thème',
    'fontSize.label': 'Taille de Police',
    'readingSpeed.label': 'Vitesse de Lecture',
    'audioSpeed.label': 'Vitesse Audio',
    'timezone.label': 'Fuseau Horaire',
    'familyMode.label': 'Mode Famille',
    'familyMode.description': 'Activer le filtrage de contenu sûr pour enfants et interface simplifiée',
    'notifications.title': 'Notifications',
    'notifications.description': 'Configurez quand et comment recevoir des rappels spirituels',
    'prayerTimes.label': 'Heures de Prière',
    'prayerTimes.description': 'Définissez vos heures préférées pour les rappels de prière',
    'quietHours.label': 'Heures Silencieuses',
    'quietHours.description': 'Aucune notification pendant ces heures',
    'offline.title': 'Contenu Hors Ligne',
    'sync.title': 'Synchronisation Multi-plateforme',
    'ai.title': 'Personnalisation IA',
    'multilingual.title': 'Contenu Multilingue',
    'multilingual.description': 'Le contenu est automatiquement traduit dans votre langue préférée tout en maintenant la précision théologique et la sensibilité culturelle.',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.auto': 'Auto',
    'fontSize.small': 'Petit',
    'fontSize.medium': 'Moyen',
    'fontSize.large': 'Grand',
    'readingSpeed.slow': 'Lent',
    'readingSpeed.medium': 'Moyen',
    'readingSpeed.fast': 'Rapide',
    'general': 'Général',
    'notifications': 'Notif.',
    'offline': 'Hors ligne',
    'sync': 'Sync',
    'ai': 'IA',
    'language': 'Langue',
    'nav.home': 'Accueil',
    'nav.messages': 'Messages',
    'nav.contacts': 'Contacts',
    'nav.churches': 'Églises',
    'nav.events': 'Événements',
    'nav.discussions': 'Discussions',
    'nav.donation': 'Don',
    'nav.todaysReading': "Lecture d'Aujourd'hui",
    'nav.prayerWall': 'Mur de Prière',
    'nav.soapJournal': 'Journal S.O.A.P.',
    'nav.audioBible': 'Bible Audio',
    'nav.audioRoutines': 'Routines Audio',
    'nav.videoLibrary': 'Bibliothèque Vidéo',
    'nav.imageGallery': "Galerie d'Images",
    'nav.memberDirectory': 'Répertoire Membres',
    'nav.donationAnalytics': 'Analyses Dons',
    'nav.communicationHub': 'Centre Communication',
    'nav.sermonStudio': 'Studio Sermon',
    'nav.engagementAnalytics': 'Analyses Engagement',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'sections.community': 'COMMUNAUTÉ',
    'sections.spiritualTools': 'OUTILS SPIRITUELS',
    'sections.mediaContents': 'CONTENU MÉDIA',
    'sections.adminPortal': 'PORTAIL ADMIN',
    'sections.account': 'COMPTE',
    'nav.engagementBoard': 'Tableau dEngagement',
    'posts.recentCheckIns': 'Enregistrements Récents',
    'posts.latestPosts': 'Dernières Publications',
    'posts.showMorePosts': 'Afficher Plus de Publications',
    'posts.pleaseShareThoughts': 'Veuillez partager vos pensées...',
    'posts.testPost': 'Publication de test',
    'posts.unableToLoadPosts': 'Impossible de charger les publications',
    'posts.loading': 'Chargement...',
    'posts.noPostsYet': 'Aucune publication pour le moment',
    'posts.beFirstToShare': 'Soyez le premier à partager quelque chose',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.submit': 'Soumettre',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'buttons.post': 'Publier',
    'buttons.like': 'Aimer',
    'buttons.comment': 'Commenter',
    'buttons.share': 'Partager',
    'posts.howAreYouFeeling': 'Comment vous sentez-vous?',
    'posts.postShared': 'Publication partagée!',
    'posts.sharedWithCommunity': 'Votre publication a été partagée avec votre communauté.',
    'pages.messages': 'Messages',
    'pages.conversations': 'Conversations',
    'pages.communityConnections': 'Connexions Communautaires',
    'pages.myChurches': 'Mes Églises',
    'pages.discoverMoreChurches': 'Découvrir Plus d\'Églises',
    'pages.communityEvents': 'Événements Communautaires',
    'pages.upcomingEvents': 'Événements À Venir',
    'pages.discussions': 'Discussions',
    'pages.todaysReading': 'Lecture d\'Aujourd\'hui',
    'pages.dailyVerse': 'Verset du Jour',
    'pages.prayerWall': 'Mur de Prière',
    'pages.prayerRequests': 'Demandes de Prière',
    'pages.prayerCircles': 'Cercles de Prière',
    'pages.analyticsAndBadges': 'Analyses et Badges',
    'pages.soapJournal': 'Journal S.O.A.P',
    'pages.audioBibleExperience': 'Expérience Bible Audio',
    'pages.audioRoutines': 'Routines Audio',
    'pages.communityEngagementBoard': 'Tableau d\'Engagement Communautaire',
    'pages.churches': 'Églises',
    'pages.events': 'Événements',
    'pages.videoLibrary': 'Bibliothèque Vidéo',
    'pages.imageGallery': 'Galerie d\'Images',
    'pages.memberDirectory': 'Répertoire des Membres',
    'pages.donationAnalytics': 'Analyses de Dons',
    'pages.communicationHub': 'Centre de Communication',
    'pages.sermonStudio': 'Studio de Sermon',
    'pages.engagementAnalytics': 'Analyses d\'Engagement',
    'pages.churchManagement': 'Gestion d\'Église',
    'pages.profile': 'Profil',
    'pages.settings': 'Paramètres',
    'common.groups': 'Groupes',
    'common.create': 'Créer',
    'common.new': 'Nouveau',
    'common.search': 'Rechercher',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'buttons.importContacts': 'Importer les Contacts',
    'buttons.inviteFriends': 'Inviter des Amis',
    'buttons.shareSoapBox': 'Partager SoapBox',
    'buttons.myContacts': 'Mes Contacts',
    'buttons.pendingInvites': 'Invitations en Attente',
    'buttons.referralProgram': 'Programme de Parrainage',
    'buttons.sendInvitation': 'Envoyer l\'Invitation',
    'buttons.copyLink': 'Copier le Lien',
    'buttons.shareLink': 'Partager le Lien',
    'buttons.viewDetails': 'Voir les Détails',
    'buttons.sendMessage': 'Envoyer un Message',
    'buttons.connect': 'Connecter',
    'buttons.remove': 'Supprimer',
    'buttons.block': 'Bloquer',
    'buttons.unblock': 'Débloquer',
    'buttons.report': 'Signaler',
    'timezone.utc': 'UTC',
    'timezone.eastern': 'Heure de l\'Est',
    'timezone.central': 'Heure Centrale',
    'timezone.mountain': 'Heure des Montagnes',
    'timezone.pacific': 'Heure du Pacifique',
    'audioEnabled.label': 'Audio Activé',
    'audioEnabled.description': 'Activer la narration audio et les effets sonores',
    'buttons.newMessage': 'Nouveau Message',
    'prayerWall.title': 'Mur de Prière',
    'prayerWall.newPrayerRequest': 'Nouvelle Demande de Prière',
    'prayerWall.categories': 'Catégories de Prière',
    'prayerWall.allPrayers': 'Toutes les Prières',
    'prayerWall.health': 'Santé',
    'prayerWall.career': 'Carrière',
    'prayerWall.relationships': 'Relations',
    'prayerWall.spiritualGrowth': 'Croissance Spirituelle',
    'prayerWall.family': 'Famille',
    'prayerWall.urgent': 'Urgent',
    'prayerWall.general': 'Général',
    'profile.title': 'Profil',
    'profile.editProfile': 'Modifier le Profil',
    'profile.statistics': 'Statistiques',
    'profile.achievements': 'Réalisations',
    'profile.contactInformation': 'Informations de Contact',
    'profile.memberSince': 'Membre depuis'
  },
  hi: {
    'settings.title': 'सेटिंग्स और प्राथमिकताएं',
    'settings.description': 'अपनी आध्यात्मिक यात्रा के अनुभव को कस्टमाइज़ करें',
    'language.title': 'भाषा और क्षेत्र',
    'language.description': 'अपनी पसंदीदा भाषा और क्षेत्रीय सेटिंग्स चुनें',
    'language.label': 'भाषा',
    'general.title': 'सामान्य प्राथमिकताएं',
    'general.description': 'अपने पढ़ने के अनुभव और इंटरफ़ेस प्राथमिकताओं को कस्टमाइज़ करें',
    'theme.label': 'थीम',
    'fontSize.label': 'फ़ॉन्ट साइज़',
    'readingSpeed.label': 'पढ़ने की गति',
    'audioSpeed.label': 'ऑडियो गति',
    'timezone.label': 'समय क्षेत्र',
    'familyMode.label': 'पारिवारिक मोड',
    'familyMode.description': 'बच्चों के लिए सुरक्षित सामग्री फ़िल्टरिंग और सरल इंटरफ़ेस सक्षम करें',
    'notifications.title': 'सूचनाएं',
    'notifications.description': 'कॉन्फ़िगर करें कि आप कब और कैसे आध्यात्मिक अनुस्मारक प्राप्त करते हैं',
    'prayerTimes.label': 'प्रार्थना समय',
    'prayerTimes.description': 'प्रार्थना अनुस्मारक के लिए अपना पसंदीदा समय सेट करें',
    'quietHours.label': 'शांत घंटे',
    'quietHours.description': 'इन घंटों के दौरान कोई सूचना नहीं',
    'offline.title': 'ऑफ़लाइन सामग्री',
    'sync.title': 'क्रॉस-प्लेटफ़ॉर्म सिंक',
    'ai.title': 'AI व्यक्तिगतकरण',
    'multilingual.title': 'बहुभाषी सामग्री',
    'multilingual.description': 'सामग्री स्वचालित रूप से आपकी पसंदीदा भाषा में अनुवादित होती है जबकि धर्मशास्त्रीय सटीकता और सांस्कृतिक संवेदनशीलता बनाए रखती है।',
    'theme.light': 'हल्का',
    'theme.dark': 'गहरा',
    'theme.auto': 'स्वचालित',
    'fontSize.small': 'छोटा',
    'fontSize.medium': 'मध्यम',
    'fontSize.large': 'बड़ा',
    'readingSpeed.slow': 'धीमा',
    'readingSpeed.medium': 'मध्यम',
    'readingSpeed.fast': 'तेज़',
    'general': 'सामान्य',
    'notifications': 'सूचनाएं',
    'offline': 'ऑफ़लाइन',
    'sync': 'सिंक',
    'ai': 'AI',
    'language': 'भाषा',
    'nav.home': 'होम',
    'nav.messages': 'संदेश',
    'nav.contacts': 'संपर्क',
    'nav.churches': 'चर्च',
    'nav.events': 'कार्यक्रम',
    'nav.discussions': 'चर्चा',
    'nav.donation': 'दान',
    'nav.todaysReading': 'आज का पठन',
    'nav.prayerWall': 'प्रार्थना दीवार',
    'nav.soapJournal': 'S.O.A.P. जर्नल',
    'nav.audioBible': 'ऑडियो बाइबल',
    'nav.audioRoutines': 'ऑडियो रूटीन',
    'nav.videoLibrary': 'वीडियो लाइब्रेरी',
    'nav.imageGallery': 'इमेज गैलरी',
    'nav.memberDirectory': 'सदस्य निर्देशिका',
    'nav.donationAnalytics': 'दान एनालिटिक्स',
    'nav.communicationHub': 'संचार केंद्र',
    'nav.sermonStudio': 'उपदेश स्टूडियो',
    'nav.engagementAnalytics': 'सहभागिता एनालिटिक्स',
    'nav.profile': 'प्रोफ़ाइल',
    'nav.settings': 'सेटिंग्स',
    'sections.community': 'समुदाय',
    'sections.spiritualTools': 'आध्यात्मिक उपकरण',
    'sections.mediaContents': 'मीडिया सामग्री',
    'sections.adminPortal': 'एडमिन पोर्टल',
    'sections.account': 'खाता',
    'nav.engagementBoard': 'सहभागिता बोर्ड',
    'posts.recentCheckIns': 'हाल की चेक-इन्स',
    'posts.latestPosts': 'नवीनतम पोस्ट',
    'posts.showMorePosts': 'और पोस्ट दिखाएं',
    'posts.pleaseShareThoughts': 'कृपया अपने विचार साझा करें...',
    'posts.testPost': 'परीक्षण पोस्ट',
    'posts.unableToLoadPosts': 'पोस्ट लोड नहीं कर सकते',
    'posts.loading': 'लोड हो रहा है...',
    'posts.noPostsYet': 'अभी तक कोई पोस्ट नहीं',
    'posts.beFirstToShare': 'कुछ साझा करने वाले पहले व्यक्ति बनें',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.submit': 'सबमिट करें',
    'common.close': 'बंद करें',
    'common.yes': 'हाँ',
    'common.no': 'नहीं',
    'buttons.post': 'पोस्ट करें',
    'buttons.like': 'पसंद',
    'buttons.comment': 'टिप्पणी',
    'buttons.share': 'साझा करें',
    'posts.howAreYouFeeling': 'आप कैसा महसूस कर रहे हैं?',
    'posts.postShared': 'पोस्ट साझा किया गया!',
    'posts.sharedWithCommunity': 'आपका पोस्ट आपके समुदाय के साथ साझा किया गया है।'
  },
  ko: {
    'settings.title': '설정 및 환경설정',
    'settings.description': '영적 여정 경험을 맞춤화하세요',
    'language.title': '언어 및 지역',
    'language.description': '선호하는 언어와 지역 설정을 선택하세요',
    'language.label': '언어',
    'general.title': '일반 환경설정',
    'general.description': '읽기 경험과 인터페이스 환경설정을 맞춤화하세요',
    'theme.label': '테마',
    'fontSize.label': '글꼴 크기',
    'readingSpeed.label': '읽기 속도',
    'audioSpeed.label': '오디오 속도',
    'timezone.label': '시간대',
    'familyMode.label': '가족 모드',
    'familyMode.description': '어린이 안전 콘텐츠 필터링 및 간단한 인터페이스 활성화',
    'notifications.title': '알림',
    'notifications.description': '영적 알림을 언제 어떻게 받을지 설정하세요',
    'prayerTimes.label': '기도 시간',
    'prayerTimes.description': '기도 알림을 위한 선호 시간을 설정하세요',
    'quietHours.label': '조용한 시간',
    'quietHours.description': '이 시간 동안 알림 없음',
    'offline.title': '오프라인 콘텐츠',
    'sync.title': '크로스 플랫폼 동기화',
    'ai.title': 'AI 개인화',
    'multilingual.title': '다국어 콘텐츠',
    'multilingual.description': '콘텐츠는 신학적 정확성과 문화적 민감성을 유지하면서 선호하는 언어로 자동 번역됩니다.',
    'theme.light': '밝음',
    'theme.dark': '어둠',
    'theme.auto': '자동',
    'fontSize.small': '작음',
    'fontSize.medium': '보통',
    'fontSize.large': '큼',
    'readingSpeed.slow': '느림',
    'readingSpeed.medium': '보통',
    'readingSpeed.fast': '빠름',
    'general': '일반',
    'notifications': '알림',
    'offline': '오프라인',
    'sync': '동기화',
    'ai': 'AI',
    'language': '언어',
    'nav.home': '홈',
    'nav.messages': '메시지',
    'nav.contacts': '연락처',
    'nav.churches': '교회',
    'nav.events': '이벤트',
    'nav.discussions': '토론',
    'nav.donation': '기부',
    'nav.todaysReading': '오늘의 읽기',
    'nav.prayerWall': '기도 벽',
    'nav.soapJournal': 'S.O.A.P. 저널',
    'nav.audioBible': '오디오 성경',
    'nav.audioRoutines': '오디오 루틴',
    'nav.videoLibrary': '비디오 라이브러리',
    'nav.imageGallery': '이미지 갤러리',
    'nav.memberDirectory': '회원 디렉토리',
    'nav.donationAnalytics': '기부 분석',
    'nav.communicationHub': '커뮤니케이션 허브',
    'nav.sermonStudio': '설교 스튜디오',
    'nav.engagementAnalytics': '참여 분석',
    'nav.profile': '프로필',
    'nav.settings': '설정',
    'sections.community': '커뮤니티',
    'sections.spiritualTools': '영적 도구',
    'sections.mediaContents': '미디어 콘텐츠',
    'sections.adminPortal': '관리자 포털',
    'sections.account': '계정',
    'nav.engagementBoard': '참여 보드',
    'posts.recentCheckIns': '최근 체크인',
    'posts.latestPosts': '최신 게시물',
    'posts.showMorePosts': '더 많은 게시물 보기',
    'posts.pleaseShareThoughts': '생각을 공유해 주세요...',
    'posts.testPost': '테스트 게시물',
    'posts.unableToLoadPosts': '게시물을 로드할 수 없습니다',
    'posts.loading': '로딩 중...',
    'posts.noPostsYet': '아직 게시물이 없습니다',
    'posts.beFirstToShare': '첫 번째로 무언가를 공유해 보세요',
    'common.cancel': '취소',
    'common.save': '저장',
    'common.edit': '편집',
    'common.delete': '삭제',
    'common.submit': '제출',
    'common.close': '닫기',
    'common.yes': '예',
    'common.no': '아니오',
    'buttons.post': '게시',
    'buttons.like': '좋아요',
    'buttons.comment': '댓글',
    'buttons.share': '공유',
    'posts.howAreYouFeeling': '기분이 어떠신가요?',
    'posts.postShared': '게시물 공유됨!',
    'posts.sharedWithCommunity': '게시물이 커뮤니티와 공유되었습니다.',
    'pages.messages': '메시지',
    'pages.conversations': '대화',
    'pages.communityConnections': '커뮤니티 연결',
    'pages.myChurches': '내 교회',
    'pages.discoverMoreChurches': '더 많은 교회 찾기',
    'pages.communityEvents': '커뮤니티 이벤트',
    'pages.upcomingEvents': '다가오는 이벤트',
    'pages.discussions': '토론',
    'pages.todaysReading': '오늘의 읽기',
    'pages.dailyVerse': '오늘의 말씀',
    'pages.prayerWall': '기도 벽',
    'pages.prayerRequests': '기도 요청',
    'pages.prayerCircles': '기도 서클',
    'pages.analyticsAndBadges': '분석 및 배지',
    'pages.soapJournal': 'S.O.A.P 저널',
    'pages.audioBibleExperience': '오디오 성경 체험',
    'pages.audioRoutines': '오디오 루틴',
    'pages.communityEngagementBoard': '커뮤니티 참여 보드',
    'pages.churches': '교회',
    'pages.events': '이벤트',
    'pages.videoLibrary': '비디오 라이브러리',
    'pages.imageGallery': '이미지 갤러리',
    'pages.memberDirectory': '회원 디렉토리',
    'pages.donationAnalytics': '기부 분석',
    'pages.communicationHub': '커뮤니케이션 허브',
    'pages.sermonStudio': '설교 스튜디오',
    'pages.engagementAnalytics': '참여 분석',
    'pages.churchManagement': '교회 관리',
    'pages.profile': '프로필',
    'pages.settings': '설정',
    'common.groups': '그룹',
    'common.create': '생성',
    'common.new': '새로운',
    'common.search': '검색',
    'common.loading': '로딩 중...',
    'common.error': '오류',
    'common.success': '성공',
    'common.confirm': '확인',
    'buttons.importContacts': '연락처 가져오기',
    'buttons.inviteFriends': '친구 초대',
    'buttons.shareSoapBox': 'SoapBox 공유',
    'buttons.myContacts': '내 연락처',
    'buttons.pendingInvites': '대기 중인 초대',
    'buttons.referralProgram': '추천 프로그램',
    'buttons.sendInvitation': '초대장 보내기',
    'buttons.copyLink': '링크 복사',
    'buttons.shareLink': '링크 공유',
    'buttons.viewDetails': '상세 보기',
    'buttons.sendMessage': '메시지 보내기',
    'buttons.connect': '연결',
    'buttons.remove': '제거',
    'buttons.block': '차단',
    'buttons.unblock': '차단 해제',
    'buttons.report': '신고',
    'timezone.utc': 'UTC',
    'timezone.eastern': '동부 시간',
    'timezone.central': '중부 시간',
    'timezone.mountain': '산악 시간',
    'timezone.pacific': '태평양 시간',
    'audioEnabled.label': '오디오 활성화',
    'audioEnabled.description': '오디오 내레이션 및 음향 효과 활성화',
    'buttons.newMessage': '새 메시지',
    'prayerWall.title': '기도 벽',
    'prayerWall.newPrayerRequest': '새 기도 요청',
    'prayerWall.categories': '기도 카테고리',
    'prayerWall.allPrayers': '모든 기도',
    'prayerWall.health': '건강',
    'prayerWall.career': '직업',
    'prayerWall.relationships': '관계',
    'prayerWall.spiritualGrowth': '영적 성장',
    'prayerWall.family': '가족',
    'prayerWall.urgent': '긴급',
    'prayerWall.general': '일반',
    'profile.title': '프로필',
    'profile.editProfile': '프로필 편집',
    'profile.statistics': '통계',
    'profile.achievements': '성취',
    'profile.contactInformation': '연락처 정보',
    'profile.memberSince': '가입일'
  },
  ar: {
    'settings.title': 'الإعدادات والتفضيلات',
    'settings.description': 'خصص تجربة رحلتك الروحية',
    'language.title': 'اللغة والمنطقة',
    'language.description': 'اختر لغتك المفضلة والإعدادات الإقليمية',
    'language.label': 'اللغة',
    'general.title': 'التفضيلات العامة',
    'general.description': 'خصص تجربة القراءة وتفضيلات الواجهة',
    'theme.label': 'المظهر',
    'fontSize.label': 'حجم الخط',
    'readingSpeed.label': 'سرعة القراءة',
    'audioSpeed.label': 'سرعة الصوت',
    'timezone.label': 'المنطقة الزمنية',
    'familyMode.label': 'وضع العائلة',
    'familyMode.description': 'تمكين تصفية المحتوى الآمن للأطفال والواجهة المبسطة',
    'notifications.title': 'الإشعارات',
    'notifications.description': 'تكوين متى وكيف تتلقى التذكيرات الروحية',
    'prayerTimes.label': 'أوقات الصلاة',
    'prayerTimes.description': 'حدد أوقاتك المفضلة لتذكيرات الصلاة',
    'quietHours.label': 'ساعات الهدوء',
    'quietHours.description': 'لا إشعارات خلال هذه الساعات',
    'offline.title': 'المحتوى غير المتصل',
    'sync.title': 'المزامنة عبر المنصات',
    'ai.title': 'التخصيص بالذكاء الاصطناعي',
    'multilingual.title': 'المحتوى متعدد اللغات',
    'multilingual.description': 'يتم ترجمة المحتوى تلقائياً إلى لغتك المفضلة مع الحفاظ على الدقة اللاهوتية والحساسية الثقافية.',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.auto': 'تلقائي',
    'fontSize.small': 'صغير',
    'fontSize.medium': 'متوسط',
    'fontSize.large': 'كبير',
    'readingSpeed.slow': 'بطيء',
    'readingSpeed.medium': 'متوسط',
    'readingSpeed.fast': 'سريع',
    'general': 'عام',
    'notifications': 'الإشعارات',
    'offline': 'غير متصل',
    'sync': 'مزامنة',
    'ai': 'ذكاء اصطناعي',
    'language': 'لغة',
    'nav.home': 'الرئيسية',
    'nav.messages': 'الرسائل',
    'nav.contacts': 'جهات الاتصال',
    'nav.churches': 'الكنائس',
    'nav.events': 'الأحداث',
    'nav.discussions': 'المناقشات',
    'nav.donation': 'التبرع',
    'nav.todaysReading': 'قراءة اليوم',
    'nav.prayerWall': 'جدار الصلاة',
    'nav.soapJournal': 'مجلة S.O.A.P.',
    'nav.audioBible': 'الكتاب المقدس الصوتي',
    'nav.audioRoutines': 'الروتين الصوتي',
    'nav.videoLibrary': 'مكتبة الفيديو',
    'nav.imageGallery': 'معرض الصور',
    'nav.memberDirectory': 'دليل الأعضاء',
    'nav.donationAnalytics': 'تحليلات التبرع',
    'nav.communicationHub': 'مركز التواصل',
    'nav.sermonStudio': 'استوديو الخطبة',
    'nav.engagementAnalytics': 'تحليلات المشاركة',
    'nav.profile': 'الملف الشخصي',
    'nav.settings': 'الإعدادات',
    'sections.community': 'المجتمع',
    'sections.spiritualTools': 'الأدوات الروحية',
    'sections.mediaContents': 'محتويات الوسائط',
    'sections.adminPortal': 'بوابة الإدارة',
    'sections.account': 'الحساب',
    'nav.engagementBoard': 'لوحة المشاركة',
    'posts.recentCheckIns': 'تسجيلات الحضور الأخيرة',
    'posts.latestPosts': 'أحدث المنشورات',
    'posts.showMorePosts': 'عرض المزيد من المنشورات',
    'posts.pleaseShareThoughts': 'من فضلك شارك أفكارك...',
    'checkins.recent': 'الحضور الأخير',
    'checkins.viewAll': 'عرض الكل',
    'checkins.quickActions': 'إجراءات سريعة',
    'checkins.checkIn': 'تسجيل الحضور',
    'checkins.viewHistory': 'عرض التاريخ',
    'posts.testPost': 'منشور تجريبي',
    'posts.unableToLoadPosts': 'غير قادر على تحميل المنشورات',
    'posts.loading': 'جاري التحميل...',
    'posts.noPostsYet': 'لا توجد منشورات بعد',
    'posts.beFirstToShare': 'كن أول من يشارك شيئاً',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'buttons.post': 'نشر',
    'buttons.like': 'إعجاب',
    'buttons.comment': 'تعليق',
    'buttons.share': 'مشاركة',
    'posts.howAreYouFeeling': 'كيف تشعر؟',
    'posts.postShared': 'تم مشاركة المنشور!',
    'posts.sharedWithCommunity': 'تم مشاركة منشورك مع مجتمعك.',
    'readingSpeed.label': 'سرعة القراءة',
    'timezone.label': 'المنطقة الزمنية',
    'audioSpeed.label': 'سرعة الصوت',
    'familyMode.label': 'وضع العائلة',
    'familyMode.description': 'إظهار محتوى ورسوم توضيحية مناسبة للأطفال',
    'audioEnabled.label': 'تمكين الصوت',
    'audioEnabled.description': 'تمكين السرد الصوتي للقراءات',
    'posts.postedBy': 'نشر بواسطة',
    'posts.timeAgo.justNow': 'الآن',
    'posts.timeAgo.minutesAgo': 'منذ دقائق',
    'posts.timeAgo.hoursAgo': 'منذ ساعات',
    'posts.timeAgo.daysAgo': 'منذ أيام',
    'posts.timeAgo.weeksAgo': 'منذ أسابيع',
    'posts.expand': 'توسيع',
    'posts.collapse': 'طي',
    'posts.readMore': 'اقرأ المزيد',
    'posts.showLess': 'عرض أقل',
    'timezone.utc': 'التوقيت العالمي المنسق',
    'timezone.eastern': 'التوقيت الشرقي',
    'timezone.central': 'التوقيت المركزي',
    'timezone.mountain': 'التوقيت الجبلي',
    'timezone.pacific': 'توقيت المحيط الهادئ',
    'readingSpeed.slow': 'بطيء',
    'readingSpeed.medium': 'عادي',
    'readingSpeed.fast': 'سريع',
    'pages.messages': 'الرسائل',
    'pages.conversations': 'المحادثات',
    'pages.communityConnections': 'الاتصالات المجتمعية',
    'pages.myChurches': 'كنائسي',
    'pages.discoverMoreChurches': 'اكتشف المزيد من الكنائس',
    'pages.communityEvents': 'فعاليات المجتمع',
    'pages.upcomingEvents': 'الأحداث القادمة',
    'pages.discussions': 'النقاشات',
    'pages.todaysReading': 'قراءة اليوم',
    'pages.dailyVerse': 'آية يومية',
    'pages.prayerWall': 'جدار الصلاة',
    'pages.prayerRequests': 'طلبات الصلاة',
    'pages.prayerCircles': 'دوائر الصلاة',
    'pages.analyticsAndBadges': 'التحليلات والشارات',
    'pages.soapJournal': 'مجلة S.O.A.P',
    'pages.audioBibleExperience': 'تجربة الكتاب المقدس الصوتي',
    'pages.audioRoutines': 'الروتين الصوتي',
    'pages.communityEngagementBoard': 'لوحة مشاركة المجتمع',
    'pages.churches': 'الكنائس',
    'pages.events': 'الأحداث',
    'pages.videoLibrary': 'مكتبة الفيديو',
    'pages.imageGallery': 'معرض الصور',
    'pages.memberDirectory': 'دليل الأعضاء',
    'pages.donationAnalytics': 'تحليلات التبرعات',
    'pages.communicationHub': 'مركز الاتصالات',
    'pages.sermonStudio': 'استوديو الوعظ',
    'pages.engagementAnalytics': 'تحليلات المشاركة',
    'pages.churchManagement': 'إدارة الكنيسة',
    'pages.profile': 'الملف الشخصي',
    'pages.settings': 'الإعدادات',
    'common.groups': 'المجموعات',
    'common.create': 'إنشاء',
    'common.new': 'جديد',
    'common.search': 'بحث',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تحرير',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.loading': 'جار التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'buttons.importContacts': 'استيراد جهات الاتصال',
    'buttons.inviteFriends': 'دعوة الأصدقاء',
    'buttons.shareSoapBox': 'مشاركة SoapBox',
    'buttons.myContacts': 'جهات اتصالي',
    'buttons.pendingInvites': 'الدعوات المعلقة',
    'buttons.referralProgram': 'برنامج الإحالة',
    'buttons.sendInvitation': 'إرسال الدعوة',
    'buttons.copyLink': 'نسخ الرابط',
    'buttons.shareLink': 'مشاركة الرابط',
    'buttons.viewDetails': 'عرض التفاصيل',
    'buttons.sendMessage': 'إرسال رسالة',
    'buttons.connect': 'اتصال',
    'buttons.remove': 'إزالة',
    'buttons.block': 'حظر',
    'buttons.unblock': 'إلغاء الحظر',
    'buttons.report': 'تبليغ',
    'timezone.utc': 'التوقيت العالمي المنسق',
    'timezone.eastern': 'التوقيت الشرقي',
    'timezone.central': 'التوقيت المركزي',
    'timezone.mountain': 'توقيت الجبال',
    'timezone.pacific': 'توقيت المحيط الهادئ',
    'audioEnabled.label': 'الصوت مفعل',
    'audioEnabled.description': 'تفعيل السرد الصوتي والمؤثرات الصوتية',
    'buttons.newMessage': 'رسالة جديدة',
    'prayerWall.title': 'جدار الصلاة',
    'prayerWall.newPrayerRequest': 'طلب صلاة جديد',
    'prayerWall.categories': 'فئات الصلاة',
    'prayerWall.allPrayers': 'جميع الصلوات',
    'prayerWall.health': 'الصحة',
    'prayerWall.career': 'المهنة',
    'prayerWall.relationships': 'العلاقات',
    'prayerWall.spiritualGrowth': 'النمو الروحي',
    'prayerWall.family': 'الأسرة',
    'prayerWall.urgent': 'عاجل',
    'prayerWall.general': 'عام',
    'profile.title': 'الملف الشخصي',
    'profile.editProfile': 'تحرير الملف الشخصي',
    'profile.statistics': 'الإحصائيات',
    'profile.achievements': 'الإنجازات',
    'profile.contactInformation': 'معلومات الاتصال',
    'profile.memberSince': 'عضو منذ'
  },
  fa: {
    'settings.title': 'تنظیمات و ترجیحات',
    'settings.description': 'تجربه سفر روحانی خود را شخصی‌سازی کنید',
    'language.title': 'زبان و منطقه',
    'language.description': 'زبان مورد نظر و تنظیمات منطقه‌ای خود را انتخاب کنید',
    'language.label': 'زبان',
    'general.title': 'ترجیحات عمومی',
    'general.description': 'تجربه خواندن و ترجیحات واسط کاربری خود را شخصی‌سازی کنید',
    'theme.label': 'تم',
    'fontSize.label': 'اندازه فونت',
    'readingSpeed.label': 'سرعت خواندن',
    'audioSpeed.label': 'سرعت صوتی',
    'timezone.label': 'منطقه زمانی',
    'familyMode.label': 'حالت خانوادگی',
    'familyMode.description': 'فعال‌سازی فیلتر محتوای ایمن برای کودکان و واسط ساده',
    'notifications.title': 'اطلاعیه‌ها',
    'notifications.description': 'تنظیم کنید چه زمانی و چگونه یادآورهای روحانی دریافت کنید',
    'prayerTimes.label': 'اوقات نماز',
    'prayerTimes.description': 'زمان‌های مورد نظر خود را برای یادآورهای نماز تنظیم کنید',
    'quietHours.label': 'ساعات سکوت',
    'quietHours.description': 'در این ساعات اطلاعیه‌ای ارسال نمی‌شود',
    'offline.title': 'محتوای آفلاین',
    'sync.title': 'همگام‌سازی چندپلتفرمه',
    'ai.title': 'شخصی‌سازی هوش مصنوعی',
    'multilingual.title': 'محتوای چندزبانه',
    'multilingual.description': 'محتوا به طور خودکار به زبان مورد نظر شما ترجمه می‌شود در حالی که دقت الهیاتی و حساسیت فرهنگی حفظ می‌شود.',
    'theme.light': 'روشن',
    'theme.dark': 'تیره',
    'theme.auto': 'خودکار',
    'fontSize.small': 'کوچک',
    'fontSize.medium': 'متوسط',
    'fontSize.large': 'بزرگ',
    'readingSpeed.slow': 'آهسته',
    'readingSpeed.medium': 'متوسط',
    'readingSpeed.fast': 'سریع',
    'general': 'عمومی',
    'notifications': 'اطلاعیه‌ها',
    'offline': 'آفلاین',
    'sync': 'همگام‌سازی',
    'ai': 'هوش مصنوعی',
    'language': 'زبان',
    'nav.home': 'خانه',
    'nav.messages': 'پیام‌ها',
    'nav.contacts': 'مخاطبین',
    'nav.churches': 'کلیساها',
    'nav.events': 'رویدادها',
    'nav.discussions': 'بحث‌ها',
    'nav.donation': 'کمک مالی',
    'nav.todaysReading': 'خواندنی امروز',
    'nav.prayerWall': 'دیوار نماز',
    'nav.soapJournal': 'ژورنال S.O.A.P.',
    'nav.audioBible': 'کتاب مقدس صوتی',
    'nav.audioRoutines': 'روال‌های صوتی',
    'nav.videoLibrary': 'کتابخانه ویدئو',
    'nav.imageGallery': 'گالری تصاویر',
    'nav.memberDirectory': 'فهرست اعضا',
    'nav.donationAnalytics': 'تحلیل کمک‌های مالی',
    'nav.communicationHub': 'مرکز ارتباطات',
    'nav.sermonStudio': 'استودیوی موعظه',
    'nav.engagementAnalytics': 'تحلیل مشارکت',
    'nav.profile': 'پروفایل',
    'nav.settings': 'تنظیمات',
    'sections.community': 'جامعه',
    'sections.spiritualTools': 'ابزارهای روحانی',
    'sections.mediaContents': 'محتوای رسانه‌ای',
    'sections.adminPortal': 'پرتال مدیریت',
    'sections.account': 'حساب کاربری',
    'nav.engagementBoard': 'تابلو مشارکت',
    'posts.recentCheckIns': 'چک‌این‌های اخیر',
    'posts.latestPosts': 'آخرین پست‌ها',
    'posts.showMorePosts': 'نمایش پست‌های بیشتر',
    'posts.pleaseShareThoughts': 'لطفاً افکار خود را به اشتراک بگذارید...',
    'posts.testPost': 'پست آزمایشی',
    'posts.unableToLoadPosts': 'امکان بارگذاری پست‌ها وجود ندارد',
    'posts.loading': 'در حال بارگذاری...',
    'posts.noPostsYet': 'هنوز پستی وجود ندارد',
    'posts.beFirstToShare': 'اولین نفری باشید که چیزی به اشتراک می‌گذارد',
    'common.cancel': 'لغو',
    'common.save': 'ذخیره',
    'common.edit': 'ویرایش',
    'common.delete': 'حذف',
    'common.submit': 'ارسال',
    'common.close': 'بستن',
    'common.yes': 'بله',
    'common.no': 'خیر',
    'buttons.post': 'پست',
    'buttons.like': 'پسندیدن',
    'buttons.comment': 'نظر',
    'buttons.share': 'اشتراک‌گذاری',
    'posts.howAreYouFeeling': 'احساس شما چگونه است؟',
    'posts.postShared': 'پست به اشتراک گذاشته شد!',
    'posts.sharedWithCommunity': 'پست شما با جامعه به اشتراک گذاشته شد.',
    'pages.messages': 'پیام‌ها',
    'pages.conversations': 'مکالمات',
    'pages.communityConnections': 'ارتباطات جامعه',
    'pages.myChurches': 'کلیساهای من',
    'pages.discoverMoreChurches': 'کشف کلیساهای بیشتر',
    'pages.communityEvents': 'رویدادهای جامعه',
    'pages.upcomingEvents': 'رویدادهای آینده',
    'pages.discussions': 'بحث‌ها',
    'pages.todaysReading': 'خواندنی امروز',
    'pages.dailyVerse': 'آیه روزانه',
    'pages.prayerWall': 'دیوار نماز',
    'pages.prayerRequests': 'درخواست‌های نماز',
    'pages.prayerCircles': 'حلقه‌های نماز',
    'pages.analyticsAndBadges': 'تحلیل و نشان‌ها',
    'pages.soapJournal': 'ژورنال S.O.A.P',
    'pages.audioBibleExperience': 'تجربه کتاب مقدس صوتی',
    'pages.audioRoutines': 'روال‌های صوتی',
    'pages.communityEngagementBoard': 'تابلو مشارکت جامعه',
    'pages.churches': 'کلیساها',
    'pages.events': 'رویدادها',
    'pages.videoLibrary': 'کتابخانه ویدئو',
    'pages.imageGallery': 'گالری تصاویر',
    'pages.memberDirectory': 'فهرست اعضا',
    'pages.donationAnalytics': 'تحلیل کمک‌های مالی',
    'pages.communicationHub': 'مرکز ارتباطات',
    'pages.sermonStudio': 'استودیوی موعظه',
    'pages.engagementAnalytics': 'تحلیل مشارکت',
    'pages.churchManagement': 'مدیریت کلیسا',
    'pages.profile': 'پروفایل',
    'pages.settings': 'تنظیمات',
    'common.groups': 'گروه‌ها',
    'common.create': 'ایجاد',
    'common.new': 'جدید',
    'common.search': 'جستجو',
    'common.loading': 'در حال بارگذاری...',
    'common.error': 'خطا',
    'common.success': 'موفقیت',
    'common.confirm': 'تأیید',
    'buttons.importContacts': 'وارد کردن مخاطبین',
    'buttons.inviteFriends': 'دعوت دوستان',
    'buttons.shareSoapBox': 'اشتراک‌گذاری SoapBox',
    'buttons.myContacts': 'مخاطبین من',
    'buttons.pendingInvites': 'دعوت‌های در انتظار',
    'buttons.referralProgram': 'برنامه ارجاع',
    'buttons.sendInvitation': 'ارسال دعوت‌نامه',
    'buttons.copyLink': 'کپی لینک',
    'buttons.shareLink': 'اشتراک‌گذاری لینک',
    'buttons.viewDetails': 'مشاهده جزئیات',
    'buttons.sendMessage': 'ارسال پیام',
    'buttons.connect': 'اتصال',
    'buttons.remove': 'حذف',
    'buttons.block': 'مسدود کردن',
    'buttons.unblock': 'رفع مسدودیت',
    'buttons.report': 'گزارش',
    'timezone.utc': 'زمان جهانی (UTC)',
    'timezone.eastern': 'زمان شرقی',
    'timezone.central': 'زمان مرکزی',
    'timezone.mountain': 'زمان کوهستانی',
    'timezone.pacific': 'زمان اقیانوس آرام',
    'audioEnabled.label': 'صدا فعال',
    'audioEnabled.description': 'فعال‌سازی روایت صوتی و جلوه‌های صوتی',
    'buttons.newMessage': 'پیام جدید',
    'prayerWall.title': 'دیوار نماز',
    'prayerWall.newPrayerRequest': 'درخواست نماز جدید',
    'prayerWall.categories': 'دسته‌بندی‌های نماز',
    'prayerWall.allPrayers': 'همه نمازها',
    'prayerWall.health': 'سلامت',
    'prayerWall.career': 'شغل',
    'prayerWall.relationships': 'روابط',
    'prayerWall.spiritualGrowth': 'رشد معنوی',
    'prayerWall.family': 'خانواده',
    'prayerWall.urgent': 'فوری',
    'prayerWall.general': 'عمومی',
    'profile.title': 'پروفایل',
    'profile.editProfile': 'ویرایش پروفایل',
    'profile.statistics': 'آمار',
    'profile.achievements': 'دستاوردها',
    'profile.contactInformation': 'اطلاعات تماس',
    'profile.memberSince': 'عضو از'
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState('en');

  // Fetch user preferences
  const { data: preferences } = useQuery({
    queryKey: ['/api/user/preferences'],
  });

  // Update language when preferences change
  useEffect(() => {
    if (preferences?.language) {
      setLanguage(preferences.language);
    }
  }, [preferences]);

  // Translation function
  const t = (key: string): string => {
    const currentTranslations = translations[language as keyof typeof translations] || translations.en;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}