-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgj9COTRoFTCerKU/P
/0WNUvKORA/lqyNTJTpDUAFuYamgCgYIKoZIzj0DAQehRANCAARSa6v/X7tvShag
/Z6KKeACA2z1Uxtp5+H1rxMRrcMAv82pLoXLFmapS07REGzB93CUSPSTY9x3M6wE
Zs4tOgZk
-----END PRIVATE KEY-----