-- Insert Reading Plan Categories
INSERT INTO reading_plan_categories (name, description) VALUES
('spiritual_growth', 'Plans focused on spiritual development and deeper faith'),
('biblical_literacy', 'Plans designed to improve Bible knowledge and understanding'),
('topical_studies', 'Plans exploring specific themes and topics in Scripture')
ON CONFLICT (name) DO NOTHING;

-- Insert Reading Plans
INSERT INTO reading_plans (name, description, duration, difficulty, category, type, created_by, created_at) VALUES
('30-Day Psalms Journey', 'Discover peace and hope through the beautiful poetry of the Psalms. This 30-day journey will guide you through selected Psalms that speak to the heart of faith, trust, and God''s faithfulness.', 30, 'beginner', 'spiritual_growth', 'topical', 'system', NOW()),
('Gospel Foundations', 'Build a solid foundation in your Christian faith by exploring the life and teachings of Jesus Christ through all four Gospels. Perfect for new believers and those wanting to rediscover Jesus.', 60, 'beginner', 'biblical_literacy', 'book_study', 'system', NOW()),
('Wisdom Literature Deep Dive', 'Gain practical wisdom for daily living through an in-depth study of Proverbs, Ecclesiastes, and Job. Learn timeless principles for making godly decisions.', 45, 'intermediate', 'biblical_literacy', 'book_study', 'system', NOW()),
('Peace in Uncertain Times', 'Find comfort and strength during difficult seasons through Scripture that speaks to anxiety, fear, and uncertainty. Discover God''s promises of peace and hope.', 21, 'beginner', 'spiritual_growth', 'topical', 'system', NOW()),
('Heroes of Faith', 'Be inspired by the incredible faith journeys of biblical heroes like Abraham, Moses, David, Esther, and Paul. Learn from their victories and failures.', 35, 'intermediate', 'spiritual_growth', 'topical', 'system', NOW()),
('New Testament Survey', 'Get the big picture of the New Testament through a comprehensive overview of all 27 books. Perfect for understanding the flow of early Christianity.', 90, 'intermediate', 'biblical_literacy', 'chronological', 'system', NOW()),
('Prayer & Worship', 'Deepen your prayer life and worship experience through Scripture that teaches us how to commune with God and live a life of praise.', 28, 'beginner', 'spiritual_growth', 'devotional', 'system', NOW());

-- Insert Reading Plan Days for "30-Day Psalms Journey"
INSERT INTO reading_plan_days (plan_id, day_number, title, scripture_reference, scripture_text, devotional_content, reflection_question, prayer_prompt) VALUES
((SELECT id FROM reading_plans WHERE name = '30-Day Psalms Journey'), 1, 'God''s Unfailing Love', 'Psalm 136:1-3', 'Give thanks to the Lord, for he is good. His love endures forever. Give thanks to the God of gods. His love endures forever. Give thanks to the Lord of lords: His love endures forever.', 'Today we begin our journey through the Psalms by recognizing the foundation of our faith: God''s unfailing love. No matter what circumstances you face, God''s love for you remains constant and eternal. This love is not based on your performance or perfection, but on His character and faithfulness.', 'How have you experienced God''s unfailing love in your life, especially during difficult times?', 'Thank God for His endless love and ask Him to help you trust in His love even when circumstances are challenging.'),

((SELECT id FROM reading_plans WHERE name = '30-Day Psalms Journey'), 2, 'Finding Refuge in God', 'Psalm 46:1-3', 'God is our refuge and strength, an ever-present help in trouble. Therefore we will not fear, though the earth give way and the mountains fall into the heart of the sea, though its waters roar and foam and the mountains quake with their surging.', 'In times of uncertainty and fear, we can find our security not in our circumstances, but in God Himself. He is described as our refuge - a place of safety and protection. When everything around us seems to be falling apart, God remains our solid foundation.', 'What situations in your life currently need God''s refuge and strength?', 'Ask God to be your refuge today and to help you find peace in His presence, regardless of external circumstances.'),

((SELECT id FROM reading_plans WHERE name = '30-Day Psalms Journey'), 3, 'The Good Shepherd', 'Psalm 23:1-4', 'The Lord is my shepherd, I lack nothing. He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul. He guides me along the right paths for his name''s sake. Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.', 'Perhaps the most beloved psalm, Psalm 23 paints a beautiful picture of God''s care for us. Like a shepherd tends his sheep, God provides for our needs, guides our paths, and protects us. Even in dark times, we don''t walk alone - our Shepherd is with us.', 'In what areas of your life do you need to trust God''s guidance and provision more fully?', 'Thank Jesus for being your Good Shepherd and ask Him to help you follow His leading in every area of your life.');

-- Insert Reading Plan Days for "Peace in Uncertain Times"
INSERT INTO reading_plan_days (plan_id, day_number, title, scripture_reference, scripture_text, devotional_content, reflection_question, prayer_prompt) VALUES
((SELECT id FROM reading_plans WHERE name = 'Peace in Uncertain Times'), 1, 'Do Not Be Anxious', 'Matthew 6:25-27', 'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes? Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them. Are you not much more valuable than they? Can any one of you by worrying add a single hour to your life?', 'Jesus'' words remind us that worry is not only unproductive but also unnecessary. Our heavenly Father, who cares for the birds of the air, surely cares for us. When we find ourselves consumed by anxiety about the future, we can choose to trust in God''s provision and care.', 'What worries are you carrying today that you need to surrender to God?', 'Ask God to help you release your anxieties and trust in His loving care and provision.'),

((SELECT id FROM reading_plans WHERE name = 'Peace in Uncertain Times'), 2, 'Perfect Peace', 'Isaiah 26:3', 'You will keep in perfect peace those whose minds are steadfast, because they trust in you.', 'God promises perfect peace to those who keep their minds focused on Him. This doesn''t mean we ignore reality or pretend problems don''t exist. Rather, it means we choose to fix our thoughts on God''s character, promises, and faithfulness instead of being consumed by our circumstances.', 'How can you practice keeping your mind steadfast on God throughout your day?', 'Pray for God to help you maintain a steadfast mind focused on Him, and ask for His perfect peace to guard your heart.'),

((SELECT id FROM reading_plans WHERE name = 'Peace in Uncertain Times'), 3, 'Casting All Cares', '1 Peter 5:7', 'Cast all your anxiety on him because he cares for you.', 'The word "cast" implies a deliberate action - throwing or hurling something away from yourself. God invites us to take all our worries, fears, and anxieties and throw them onto Him. Why? Because He genuinely cares for us. Our concerns matter to Him because we matter to Him.', 'What specific anxieties do you need to cast upon God right now?', 'Deliberately cast each of your worries upon God, thanking Him that He cares for you and will handle what concerns you.');

-- Insert sample days for other plans (abbreviated for space)
INSERT INTO reading_plan_days (plan_id, day_number, title, scripture_reference, devotional_content, reflection_question, prayer_prompt) VALUES
((SELECT id FROM reading_plans WHERE name = 'Gospel Foundations'), 1, 'The Word Became Flesh', 'John 1:1-14', 'Begin your journey into the Gospels by understanding who Jesus is - the eternal Word of God who became human to dwell among us.', 'What does it mean to you that Jesus, being God, chose to become human?', 'Thank Jesus for leaving heaven to come to earth and ask Him to reveal Himself to you through this study.'),

((SELECT id FROM reading_plans WHERE name = 'Wisdom Literature Deep Dive'), 1, 'The Fear of the Lord', 'Proverbs 1:7', 'True wisdom begins with a proper reverence and awe for God. This foundational principle will guide all our learning.', 'How would you describe your current relationship with God - is it characterized by reverent awe?', 'Ask God to give you a heart that fears Him in the biblical sense - with reverence, awe, and respect.'),

((SELECT id FROM reading_plans WHERE name = 'Heroes of Faith'), 1, 'Abraham''s Call', 'Genesis 12:1-4', 'Abraham''s journey of faith began with a call from God to leave everything familiar and trust in God''s promises.', 'What might God be calling you to leave behind in order to follow Him more fully?', 'Pray for the faith to follow God''s leading, even when the path is uncertain.');